Repository MicroFocus/ADM-FT-ToolsLauncher, pull requests merged in 2021-07, with the labels that each got.

#51 Fix bug that can't convert result when no iteration node exists
  ReportConverter/ReportConverter.csproj
  ReportConverter/XmlReport/GUITest/TestReport.cs
Labels: bug

#52 Add parameter to populate test name only in results summary file
  HpToolsLauncher/Interfaces/IXmlBuilder.cs
  HpToolsLauncher/JunitXml/JunitXmlBuilder.cs
  HpToolsLauncher/Launcher.cs
  HpToolsLauncher/Properties/AssemblyInfo.cs
  README.md
Labels: enhancement

#54 Update release utils for v1.0 beta (rev.7)
  utils/generate_release_desc.ps1
Labels: release

#55 641023 [ADO] Have ALM Lab Mgmt task run on ALM configured host
  HpToolsLauncher/HpToolsLauncher.csproj
  HpToolsLauncher/Runners/AlmTestSetsRunner.cs
  HpToolsLauncher/app.config
Labels: optimization
